name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: "Check out repository"
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
          with:
            node-version 'lts/*'
      - name: Install dépendance
        run: npm install
        
